<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="A book about autoregressive LLM inference and the techniques that make it fast, efficient, and scalable">

<title>3&nbsp; Measuring LLM Inference – LLM Inference Illustrated</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/model-design.html" rel="next">
<link href="../chapters/decoder-only-llm.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../_styles/dim-colors.css">
<meta name="twitter:title" content="3&nbsp; Measuring LLM Inference – LLM Inference Illustrated">
<meta name="twitter:description" content="A book about autoregressive LLM inference and the techniques that make it fast, efficient, and scalable">
<meta name="twitter:image" content="images/pipeline_stages.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/inference.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring LLM Inference</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">LLM Inference Illustrated</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/tedkyi/llm-inference/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cover</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/conventions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conventions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/decoder-only-llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Decoder-Only Transformer</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring LLM Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/model-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Model Design Choices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/scheduling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Scheduling Bottlenecks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/request.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Request Compute, Memory, and Latency Bottlenecks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Scaling Across Hardware</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Production LLM Serving Systems</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-inference-pipeline" id="toc-sec-inference-pipeline" class="nav-link active" data-scroll-target="#sec-inference-pipeline"><span class="header-section-number">3.1</span> The Inference Pipeline</a>
  <ul class="collapse">
  <li><a href="#sec-pipeline-stages" id="toc-sec-pipeline-stages" class="nav-link" data-scroll-target="#sec-pipeline-stages">The stages of inference</a></li>
  <li><a href="#where-the-time-goes" id="toc-where-the-time-goes" class="nav-link" data-scroll-target="#where-the-time-goes">Where the time goes</a></li>
  <li><a href="#two-fundamentally-different-regimes" id="toc-two-fundamentally-different-regimes" class="nav-link" data-scroll-target="#two-fundamentally-different-regimes">Two fundamentally different regimes</a></li>
  </ul></li>
  <li><a href="#sec-metrics" id="toc-sec-metrics" class="nav-link" data-scroll-target="#sec-metrics"><span class="header-section-number">3.2</span> Performance Metrics</a>
  <ul class="collapse">
  <li><a href="#user-facing-latency-metrics" id="toc-user-facing-latency-metrics" class="nav-link" data-scroll-target="#user-facing-latency-metrics">User-facing latency metrics</a></li>
  <li><a href="#throughput" id="toc-throughput" class="nav-link" data-scroll-target="#throughput">Throughput</a></li>
  <li><a href="#the-latencythroughput-tradeoff" id="toc-the-latencythroughput-tradeoff" class="nav-link" data-scroll-target="#the-latencythroughput-tradeoff">The latency–throughput tradeoff</a></li>
  <li><a href="#goodput" id="toc-goodput" class="nav-link" data-scroll-target="#goodput">Goodput</a></li>
  <li><a href="#cost-efficiency" id="toc-cost-efficiency" class="nav-link" data-scroll-target="#cost-efficiency">Cost efficiency</a></li>
  <li><a href="#hardware-utilization-metrics" id="toc-hardware-utilization-metrics" class="nav-link" data-scroll-target="#hardware-utilization-metrics">Hardware utilization metrics</a></li>
  <li><a href="#capacity-metrics" id="toc-capacity-metrics" class="nav-link" data-scroll-target="#capacity-metrics">Capacity metrics</a></li>
  <li><a href="#preemption-metrics" id="toc-preemption-metrics" class="nav-link" data-scroll-target="#preemption-metrics">Preemption metrics</a></li>
  <li><a href="#putting-it-all-together" id="toc-putting-it-all-together" class="nav-link" data-scroll-target="#putting-it-all-together">Putting it all together</a></li>
  </ul></li>
  <li><a href="#sec-workloads" id="toc-sec-workloads" class="nav-link" data-scroll-target="#sec-workloads"><span class="header-section-number">3.3</span> Workload Patterns</a>
  <ul class="collapse">
  <li><a href="#the-inputoutput-quadrants" id="toc-the-inputoutput-quadrants" class="nav-link" data-scroll-target="#the-inputoutput-quadrants">The input/output quadrants</a></li>
  <li><a href="#why-the-quadrants-matter" id="toc-why-the-quadrants-matter" class="nav-link" data-scroll-target="#why-the-quadrants-matter">Why the quadrants matter</a></li>
  <li><a href="#batch-vs.-real-time-inference" id="toc-batch-vs.-real-time-inference" class="nav-link" data-scroll-target="#batch-vs.-real-time-inference">Batch vs.&nbsp;real-time inference</a></li>
  <li><a href="#arrival-patterns" id="toc-arrival-patterns" class="nav-link" data-scroll-target="#arrival-patterns">Arrival patterns</a></li>
  </ul></li>
  <li><a href="#sec-bottleneck-framework" id="toc-sec-bottleneck-framework" class="nav-link" data-scroll-target="#sec-bottleneck-framework"><span class="header-section-number">3.4</span> The Hardware Model and Bottleneck Framework</a>
  <ul class="collapse">
  <li><a href="#gpu-compute-throughput" id="toc-gpu-compute-throughput" class="nav-link" data-scroll-target="#gpu-compute-throughput">GPU compute throughput</a></li>
  <li><a href="#the-memory-hierarchy" id="toc-the-memory-hierarchy" class="nav-link" data-scroll-target="#the-memory-hierarchy">The memory hierarchy</a></li>
  <li><a href="#cpu-gpu-interaction-and-kernel-launch-overhead" id="toc-cpu-gpu-interaction-and-kernel-launch-overhead" class="nav-link" data-scroll-target="#cpu-gpu-interaction-and-kernel-launch-overhead">CPU-GPU interaction and kernel launch overhead</a></li>
  <li><a href="#the-bottleneck-framework" id="toc-the-bottleneck-framework" class="nav-link" data-scroll-target="#the-bottleneck-framework">The bottleneck framework</a></li>
  <li><a href="#the-roofline-model" id="toc-the-roofline-model" class="nav-link" data-scroll-target="#the-roofline-model">The roofline model</a></li>
  </ul></li>
  <li><a href="#sec-prefill-decode" id="toc-sec-prefill-decode" class="nav-link" data-scroll-target="#sec-prefill-decode"><span class="header-section-number">3.5</span> Putting Numbers on a Baseline</a>
  <ul class="collapse">
  <li><a href="#sec-prefill-stage" id="toc-sec-prefill-stage" class="nav-link" data-scroll-target="#sec-prefill-stage">Prefill is compute-bound</a></li>
  <li><a href="#sec-decode-stage" id="toc-sec-decode-stage" class="nav-link" data-scroll-target="#sec-decode-stage">Decode is memory-bandwidth-bound</a></li>
  <li><a href="#the-kv-cache-adds-to-reads-and-writes" id="toc-the-kv-cache-adds-to-reads-and-writes" class="nav-link" data-scroll-target="#the-kv-cache-adds-to-reads-and-writes">The KV cache adds to reads and writes</a></li>
  <li><a href="#batching-changes-the-picture" id="toc-batching-changes-the-picture" class="nav-link" data-scroll-target="#batching-changes-the-picture">Batching changes the picture</a></li>
  <li><a href="#back-of-envelope-summary" id="toc-back-of-envelope-summary" class="nav-link" data-scroll-target="#back-of-envelope-summary">Back-of-envelope summary</a></li>
  </ul></li>
  <li><a href="#map-of-the-optimizations" id="toc-map-of-the-optimizations" class="nav-link" data-scroll-target="#map-of-the-optimizations"><span class="header-section-number">3.6</span> Map of the optimizations</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">3.7</span> Further Reading</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/tedkyi/llm-inference/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-framing" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Measuring LLM Inference</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Now that we are familiar with the decoder-only LLM and how data flows through it, let’s go deeper into the autoregressive nature of standard text generation and discuss how to quantify its performance. We will develop an understanding of the stages of inference, how we measure inference, and the performance model that underlies our computing hardware, in particular GPUs.</p>
<section id="sec-inference-pipeline" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-inference-pipeline"><span class="header-section-number">3.1</span> The Inference Pipeline</h2>
<p>From the time you send a prompt to an LLM until you get a response back, a lot happens between those two moments. The full journey of a single request breaks down into a few stages. Some of these are one-time setup costs, some happen once per request, and some repeat for every output token. Understanding the characteristics of the stages will help you focus your attention on the ones that actually dominate wall-clock time. In this section, as with most of the book, we will assume the LLM is running on a computer with a GPU. The principles will be the same if it is running on CPU, TPU, or other hardware.</p>
<section id="sec-pipeline-stages" class="level3">
<h3 class="anchored" data-anchor-id="sec-pipeline-stages">The stages of inference</h3>
<p>Let’s walk through the stages needed to process a user request. We will break this down into four stages that have distinct properties in terms of when they happen, where they happen, and what kinds of resources they consume. These stages are shown in <a href="#fig-pipeline-stages" class="quarto-xref">Figure&nbsp;<span>3.1</span></a>.</p>
<div id="fig-pipeline-stages" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-stages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/pipeline_stages.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;3.1: The stages of LLM inference for a single request. Ingestion and response completion are fast. Prefill and decode dominate wall-clock time."><img src="images/pipeline_stages.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-stages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: The stages of LLM inference for a single request. Ingestion and response completion are fast. Prefill and decode dominate wall-clock time.
</figcaption>
</figure>
</div>
<p>We will assume the model is already loaded into GPU main memory. For a 70-billion-parameter model stored in FP16 (2 bytes per parameter), the weights alone are about 140 GB. Loading that volume of data from an NVMe SSD at 7 GB/s takes about 20 seconds, and from a network file system, it could take longer. Because this is so slow, on typical inference software, the weights are loaded into GPU memory at startup and they stay there for the lifetime of the serving session.</p>
<p><strong>Ingestion</strong> is the entry point for each request. The system takes your prompt and forms a new request. Your prompt may be merged with other content, such as a system prompt. Next, this finalized raw text is tokenized — converted from characters into the integer token IDs that the model actually works with — and any additional validation or preprocessing is applied. This stage is fast compared to the resource-intensive work involving the neural network model that follows and is typically handled on the CPU. This stage may also involve queuing. In a production system, requests may wait in a queue until there are resources available to process them, and if the system has multiple priority levels, lower priority requests may wait longer. We are skipping many details about the steps within ingestion because what they have in common is that they usually happen once and are relatively fast. One area where ingestion has a dramatic impact on speed and user experience is in the timing and granularity of scheduling request work, and we will discuss scheduling in <a href="scheduling.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
<p><strong>Prefill</strong> is where the heavy lifting begins. The model processes the entire set of input tokens in a single forward pass through the entire network — all layers, all attention heads, all FFN blocks. In particular, the attention layers calculate attention scores across all of the input tokens. Since the attention scores are a square whose sides are the number of tokens, this grows quadratically with respect to the sequence length, and it becomes very expensive when there are many input tokens. Because all input tokens are known up front, the attention calculation can be done all at once using a large matrix-matrix multiplication between queries and keys. Despite how efficiently modern GPUs perform matrix multiplication, the size of the matrices involved means that prefill for all but the shortest prompts is <strong>compute-bound</strong> — the bottleneck is how fast the GPU can do the arithmetic, not how fast it can move data into the computational cores.</p>
<p>During prefill, each attention layer computes query, key, and value tensors for all of the input tokens. The keys and values will be needed again in the upcoming decoding stage. Rather than throwing these away and recomputing them during decoding, the system stores them in the <strong>KV cache</strong>, which we introduced in <a href="decoder-only-llm.html#sec-kv-cache-intro" class="quarto-xref"><span>Section 2.5</span></a>. Initializing the KV cache is the primary function of the prefill stage in modern LLM serving systems. The KV cache holds the key and value tensors for every attention head at every layer, for all tokens processed so far. The KV cache trades memory for compute: it uses GPU memory to store these tensors, but it eliminates the need to recompute them. The size of the KV cache created during prefill is:</p>
<p><span class="math display">\[\text{KV cache memory} = 2 \times \textcolor{#8B4513}{L} \times \textcolor{#C084FC}{H_{\text{KV}}} \times \textcolor{#DC2626}{S} \times \textcolor{#2563EB}{d_K} \times b\]</span></p>
<p>where the factor of 2 accounts for storing both keys and values, <strong><span class="dim-l">L</span></strong> is the number of layers, <span class="math inline">\(\textcolor{#C084FC}{H_{\text{KV}}}\)</span> is the number of key-value heads (which may be less than the number of query heads, as will be discussed in <a href="model-design.html#sec-efficient-attention" class="quarto-xref"><span>Section 4.4</span></a>), <strong><span class="dim-s">S</span></strong> is the current sequence length, <span class="math inline">\(\textcolor{#2563EB}{d_K}\)</span> is the dimension of each head, and <span class="math inline">\(b\)</span> is the number of bytes per element (2 for FP16/BF16).</p>
<p>For a concrete example, consider a Llama-style 70B model with 80 layers, 8 KV heads per layer, head dimension of 128, and FP16 KV cache entries (2 bytes each). For a 4,096-token prompt:</p>
<p><span class="math display">\[\text{KV cache} = 2 \times 80 \times 8 \times 4096 \times 128 \times 2 \approx 1.34 \text{ GB}\]</span></p>
<p>That’s 1.34 GB of GPU memory consumed by a single request’s KV cache, just from the input tokens. This memory usage is one of the primary constraints on how many requests can be served concurrently, which we’ll explore in <a href="model-design.html#sec-efficient-attention" class="quarto-xref"><span>Section 4.4</span></a>, <a href="request.html#sec-kv-cache" class="quarto-xref"><span>Section 6.3</span></a>, and other sections.</p>
<p>After prefill completes, the system has two things: the KV cache populated with entries for all input tokens and the logits for the last input position’s next token prediction, which are used to generate the first output token.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a detailed look at exactly how the key, value, and query projections are computed during the transformer’s forward pass and how they relate to the KV cache, see sections <a href="decoder-only-llm.html#sec-self-attention" class="quarto-xref"><span>2.4</span></a> and <a href="decoder-only-llm.html#sec-kv-cache-intro" class="quarto-xref"><span>2.5</span></a>.</p>
</div>
</div>
<p><strong>Decode</strong> is the phase where the LLM’s response is generated (except for the first token). The model typically produces output tokens one at a time, where each new token depends on all previously generated tokens. This sequential dependency comes from how the model defines the probability of an output sequence. Given input tokens <span class="math inline">\(x\)</span>, the probability of generating output sequence <span class="math inline">\(y = (y_1, y_2, \ldots, y_T)\)</span> is decomposed using the chain rule of probability, where each output token’s probability distribution is conditioned on both the prompt <span class="math inline">\(x\)</span> and all of the prior output tokens:</p>
<p><span class="math display">\[p(y \mid x) = \prod_{t=1}^{T} p(y_t \mid y_{&lt;t}, x)\]</span></p>
<p>The model estimates each conditional probability <span class="math inline">\(p(y_t \mid y_{&lt;t}, x)\)</span> with a forward pass. Because each token’s probability depends on all previously generated tokens, the model doesn’t generate token <span class="math inline">\(y_t\)</span> until it has committed to tokens <span class="math inline">\(y_1\)</span> through <span class="math inline">\(y_{t-1}\)</span>. This gives us the familiar autoregressive loop:</p>
<ul>
<li>Run a forward pass for one new token, reading all active weights and the full KV cache</li>
<li>Obtain the logit distribution over the vocabulary</li>
<li>Sample a token</li>
<li>Append new key-value entries to the KV cache, and</li>
<li>Repeat until the model generates a stop token or hits a length limit</li>
</ul>
<p>Each iteration of this basic loop is called a <strong>decode step</strong>. The forward pass in a decode step processes just one token (or one token per batch entry, in a batch), so the query-key operations are <strong>matrix-vector multiplications</strong> rather than the matrix-matrix multiplications of prefill. The keys are still a matrix of <strong><span class="dim-s">S</span></strong> vectors, but now they’re being multiplied by a single query vector instead of a matrix of <strong><span class="dim-s">S</span></strong> vectors.</p>
<p>The one-token-at-a-time nature of typical decoding is the central challenge of LLM inference. Each decode step involves reading all the model weights and the full KV cache, but only to compute a single token’s worth of output. The ratio of computation to data movement is very low, which makes decode steps typically <strong>memory-bandwidth-bound</strong>. Here, the bottleneck is how fast the GPU can read data from GPU memory, not how fast it can do math. A large portion of this book is about techniques to make this phase less painful.</p>
<p>It’s worth noting that the left-to-right, one-token-at-a-time autoregressive factorization is not the <em>only</em> mathematically valid way to express the joint probability of a sequence. There are other approaches that calculate the same joint distribution differently. The left-to-right decomposition is a convenient modeling choice, but it imposes a strict sequential dependency at inference time. Several techniques in <a href="request.html#sec-speculative" class="quarto-xref"><span>Section 6.5</span></a> — speculative decoding, multi-token prediction, and Medusa heads — work by finding ways to break or shortcut this sequential dependency while preserving the same output distribution.</p>
<p>At the end of each decode step, <strong>sampling</strong> selects the next token. After the forward pass has produced a logit vector over the vocabulary, one token ID is selected. Common strategies include:</p>
<ul>
<li>greedy decoding (always pick the highest-probability token),</li>
<li>temperature sampling (scale logits before sampling randomly),</li>
<li>top-k sampling (restrict to the <span class="math inline">\(k\)</span> most probable tokens), and</li>
<li>top-p / nucleus sampling (restrict sampling to the smallest set of tokens whose cumulative probability exceeds <span class="math inline">\(p\)</span>)</li>
</ul>
<p>Sampling adds negligible overhead relative to the preceding forward pass. The forward pass involves billions of multiply-accumulate operations across all the model’s layers; sampling involves a softmax over the vocabulary (typically 30K-200K entries) and a random draw. Sampling is not where the time goes.</p>
<p><strong>Completion</strong> wraps things up. The model has finished because it either generated a stop token, hit a maximum length limit, or has been interrupted by the serving system. The accumulated response is detokenized back into text, the KV cache memory is freed, and the result is returned to the user. In most production deployments, the response is <strong>streamed</strong> back to the user as tokens are generated, rather than waiting for the full response to complete. Streaming doesn’t change what’s happening on the GPU — each decode step produces the same token whether it’s streamed immediately or batched for delivery later — but it reduces how long users have to wait to see the beginning of the LLM response. Whether batch or streaming, completion steps are like ingestion in that they are usually fast one-time operations that happen on the CPU.</p>
</section>
<section id="where-the-time-goes" class="level3">
<h3 class="anchored" data-anchor-id="where-the-time-goes">Where the time goes</h3>
<p>Of the five stages above, the vast majority of compute and memory bandwidth is consumed by prefill and decode. Model loading is a one-time cost. Ingestion and completion are fast operations on CPU that together account for a tiny fraction of request latency. Note that we are excluding queueing time from ingestion for now, treating that as a fixed cost associated with workload. Queueing time can be long for a system under heavy load, and various techniques associated with scheduling are discussed in <a href="scheduling.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
</section>
<section id="two-fundamentally-different-regimes" class="level3">
<h3 class="anchored" data-anchor-id="two-fundamentally-different-regimes">Two fundamentally different regimes</h3>
<p>While prefill and decode are both expensive, the contrast between the types of resources they need is worth emphasizing.</p>
<p>During prefill, we have a large set of tokens to process, so we can keep the GPU’s compute units busy with very large matrix multiplications. During decode, we’re typically generating one token at a time, so we need many forward passes which each require much smaller computations that mostly involve reading a lot of data.</p>
<p>This means prefill and decode need different resources from the hardware. Prefill wants raw compute horsepower. Decode wants memory bandwidth. As we’ll see in <a href="#sec-bottleneck-framework" class="quarto-xref"><span>Section 3.4</span></a>, the roofline model gives us a precise way to reason about where the boundary between these two bottlenecks falls for a given GPU or hardware accelerator.</p>
<p>Many of the optimizations covered in this book target just prefill or just decode, and some of the techniques span between the two of them. Understanding the fundamental difference in resource needs between prefill and decode will provide a good foundation for everything that follows.</p>
</section>
</section>
<section id="sec-metrics" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-metrics"><span class="header-section-number">3.2</span> Performance Metrics</h2>
<p>Now that we have a mental model of what happens during inference, the natural next question is: how do we know if our system is doing it <em>well</em>? This section introduces the metrics you’ll encounter throughout the rest of the book. We’ll group them by what they measure, because different concerns utilize different metrics.</p>
<section id="user-facing-latency-metrics" class="level3">
<h3 class="anchored" data-anchor-id="user-facing-latency-metrics">User-facing latency metrics</h3>
<p>The metrics that matter most in interactive applications are the ones users actually feel.</p>
<p><strong>Time to First Token (TTFT)</strong> is the wall-clock time from when a request is submitted to when the first output token is produced. In a chat application, this is how long the user stares at a blank screen before text starts appearing. TTFT is significantly impacted by the duration of the prefill phase because ingestion usually is fast, we don’t need to decode many tokens to start returning text to the user, and completion is also fast. Since the system has to process the entire input before it can begin generating any output, longer prompts mean longer prefill, which means higher TTFT.</p>
<p>Note that TTFT isn’t as simple as the prefill duration plus fixed costs for the other phases. In systems under heavy load, the request may sit in a queue before being serviced. Also, in streaming deployments, the first token might be generated by the model but not immediately delivered to the user. Tokens can be buffered for various reasons, including network batching, detokenization requiring multiple tokens to resolve a word boundary, or framework-level batching of streamed chunks. So the TTFT the user experiences can be somewhat higher than the time the inference engine measures internally for prefill and generation of the first token.</p>
<p><strong>Time Per Output Token (TPOT)</strong>, also called <strong>Inter-Token Latency (ITL)</strong>, is the average time between successive output tokens during generation. This is what governs how fast text appears to stream after that first token shows up. TPOT is a function of the decode process. When each decode step produces one token, TPOT is essentially the time per decode step. For a fluent reading experience in interactive applications, you generally want TPOT below about 50–100 milliseconds. Go much higher and the output starts to feel sluggish.</p>
<p>TPOT is an average, and individual decode steps can vary. The KV cache grows with each token, so later decode steps read slightly more data than earlier ones. In practice, this variation is usually small relative to the total step time, but it can matter for very long sequences.</p>
<div id="fig-ttft-tpot" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ttft-tpot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/ttft_tpot_timeline.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;3.2: Request timeline showing TTFT and TPOT durations"><img src="images/ttft_tpot_timeline.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ttft-tpot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2: Request timeline showing TTFT and TPOT durations
</figcaption>
</figure>
</div>
<p>Together, TTFT and TPOT define the end-to-end latency of a request, as shown in <a href="#fig-ttft-tpot" class="quarto-xref">Figure&nbsp;<span>3.2</span></a>. The total time to generate a response of <span class="math inline">\(N\)</span> output tokens is approximately <span class="math inline">\(\text{TTFT} + (N - 1) \times \text{TPOT}\)</span>. For short outputs, TTFT dominates. For long outputs, TPOT dominates. This is why the workload shape — the ratio of input length to output length — matters so much for understanding metrics and performing optimizations, as we’ll discuss in <a href="#sec-workloads" class="quarto-xref"><span>Section 3.3</span></a>.</p>
</section>
<section id="throughput" class="level3">
<h3 class="anchored" data-anchor-id="throughput">Throughput</h3>
<p>While latency metrics describe the experience of a single request, <strong>throughput</strong> measures how much total work the system gets done. The most common unit is <strong>tokens per second (TPS)</strong> — specifically, output tokens per second combined across all requests currently being served. You’ll also see <strong>requests per second (RPS)</strong> and <strong>requests per minute (RPM)</strong>, which measure how many complete requests the system finishes in a given time window. Note that a system processing one request that generates 100 tokens per second has 100 TPS, and a system processing 100 requests that each generate 1 token per second also has 100 TPS. RPS is highly dependent on the workload.</p>
</section>
<section id="the-latencythroughput-tradeoff" class="level3">
<h3 class="anchored" data-anchor-id="the-latencythroughput-tradeoff">The latency–throughput tradeoff</h3>
<p>Latency and throughput are in fundamental tension, and this tradeoff is at the heart of inference system configuration.</p>
<p>One key mechanism impacting latency and throughput is <strong>batching</strong>. If you process requests one at a time, each request gets the lowest possible latency while being serviced — there’s no waiting to fill a batch, and the hardware is entirely dedicated to that single request. But the GPU is badly underutilized, especially during decode, where a single request doesn’t generate enough arithmetic to keep the compute units busy.</p>
<p>If instead you batch multiple requests together, the GPU can do more useful work per memory read. Reading the model weights once and applying them to 32 requests in a batch is far more efficient than reading them 32 separate times. With larger batches, throughput goes up, but now each individual request might have to wait before processing begins, because the system is pausing to accumulate enough requests for a full batch. Also, each decode step takes slightly longer because there’s more work per step, so with larger batches, latency goes up a little.</p>
<div id="fig-throughput-latency" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-throughput-latency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/latency_throughput.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3.3: Throughput-latency curve showing how throughput gains diminish as latency increases. Data from @spheron2025benchmarks, benchmarking Llama 3.3 70B (FP8) on a single H100 system running vLLM."><img src="images/latency_throughput.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-throughput-latency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.3: Throughput-latency curve showing how throughput gains diminish as latency increases. Data from <span class="citation" data-cites="spheron2025benchmarks">Spheron (<a href="references.html#ref-spheron2025benchmarks" role="doc-biblioref">2025</a>)</span>, benchmarking Llama 3.3 70B (FP8) on a single H100 system running vLLM.
</figcaption>
</figure>
</div>
<p>This tradeoff is not just theoretical. In production serving, batch configuration significantly impacts scheduler performance, as shown in <a href="#fig-throughput-latency" class="quarto-xref">Figure&nbsp;<span>3.3</span></a>. A scheduler that waits longer to fill batches achieves higher throughput but increases TTFT for waiting requests. A scheduler that dispatches immediately may keep TTFT lower but hurts throughput. Finding the right operating point depends on the application’s requirements, which is where the next metric comes in.</p>
</section>
<section id="goodput" class="level3">
<h3 class="anchored" data-anchor-id="goodput">Goodput</h3>
<p>Raw throughput doesn’t tell the whole story. <strong>Goodput</strong> is throughput counting only responses that actually meet the application’s requirements — its service-level agreement (SLA). The SLA for a chat application might specify a maximum TTFT, a maximum TPOT, a maximum end-to-end latency, or some combination of these.</p>
<p>A system can have impressive throughput numbers but poor goodput. If you push batch sizes so high that 30% of requests exceed the latency budget, those requests don’t count toward goodput, even though the system did the work. Similarly, if the system is so overloaded that it starts preempting or dropping requests, the raw TPS might look fine while the actual useful output is much lower. Goodput is the metric that connects basic system performance to whether users are actually getting a good experience.</p>
</section>
<section id="cost-efficiency" class="level3">
<h3 class="anchored" data-anchor-id="cost-efficiency">Cost efficiency</h3>
<p>At scale, inference cost is often a key optimization target. <strong>Cost per token</strong> measures how much it costs in dollars (or GPU-hours) to generate one output token. It’s roughly inversely proportional to throughput — if you double your throughput on the same hardware, you halve your cost per token. This means that most of the techniques covered in this book that improve throughput will reduce cost.</p>
<p>The picture gets more nuanced when you factor in different hardware devices (each with different cost and performance profiles), different precision formats, and the amortized cost of hardware across many workloads. But as a first approximation, optimizing for throughput is optimizing for cost.</p>
</section>
<section id="hardware-utilization-metrics" class="level3">
<h3 class="anchored" data-anchor-id="hardware-utilization-metrics">Hardware utilization metrics</h3>
<p>The metrics above describe what the system achieves. The next two measure how efficiently it uses the hardware to get there. To diagnose whether or not you’re maximizing the capabilities of your hardware, you need different metrics.</p>
<p><strong>Model FLOPs Utilization (MFU)</strong> is the fraction of the GPU’s peak floating-point throughput that is actually used for model computation. This metric was introduced in the PaLM paper <span class="citation" data-cites="chowdhery2022palm">(<a href="references.html#ref-chowdhery2022palm" role="doc-biblioref"><span class="nocase">Chowdhery et al.</span> 2022</a>)</span> and has become a standard efficiency metric. If your GPU can do 990 TFLOP/s at FP16, and your model computation actually achieves 300 TFLOP/s, your MFU is about 30%.</p>
<p>MFU is most useful for characterizing compute-bound workloads like prefill. A low MFU during prefill suggests that something is preventing the GPU from doing math at full speed — perhaps memory transfers, kernel launch overhead, or poorly shaped matrix multiplications. We’ll see how to use the roofline model to reason about this precisely in <a href="#sec-bottleneck-framework" class="quarto-xref"><span>Section 3.4</span></a>.</p>
<p><strong>Model Bandwidth Utilization (MBU)</strong> is the analogous metric for memory bandwidth. MBU is the fraction of peak memory bandwidth that is actually used for reading model data. During decode, the bottleneck is typically how fast you can stream model weights and KV cache entries from HBM. If your GPU has 3.35 TB/s of HBM bandwidth and your decode step actually achieves 2.5 TB/s, your MBU is about 75%.</p>
<p>MBU is a good diagnostic for decode activity. A low MBU during decode means the memory system is not being fully utilized — perhaps due to small batch sizes, kernel launch gaps between layers, or overhead from memory management. Together, MFU and MBU give you a quick read on whether your system is limited by compute efficiency, memory bandwidth efficiency, or something else entirely. Note that manufacturers often report peak compute and bandwidth numbers on very specific workloads that yield the highest numbers. You should not expect to get close to 100% MFU or MBU for real-world use cases.</p>
</section>
<section id="capacity-metrics" class="level3">
<h3 class="anchored" data-anchor-id="capacity-metrics">Capacity metrics</h3>
<p>These metrics describe the system’s resource utilization.</p>
<p><strong>Concurrency</strong> is the average number of in-flight requests the system is serving simultaneously. This is primarily constrained by GPU memory: each active request needs space for its KV cache, and the KV cache grows with sequence length. If your GPU has 80 GB of HBM and your model weights consume 30 GB, you have roughly 50 GB left for KV caches (minus some overhead). How many requests fit in that budget depends on the model architecture, the precision of the KV cache, and how long the sequences are. The scheduler policy dictates whether to reserve memory conservatively or to pack it more aggressively and risk running out of memory.</p>
<p><strong>GPU memory usage</strong> is the average amount of GPU memory that is being used. Usage is comprised of four components: model weights, KV cache, activations temporarily stored during the forward pass, and framework overhead (memory allocated by the CUDA runtime, the serving framework, and so on). The weights are fixed once the model is loaded. Activations are transient and relatively small. The KV cache is the variable that dominates, and it scales with both concurrency and sequence length.</p>
<p><strong>Maximum sequence length supported</strong> is the longest sequence (counting both input and output tokens) that the system can handle. Note that even if the model was trained to support 128K tokens, your deployment might be limited to 32K if that’s all the KV cache memory you can afford while maintaining your target concurrency. This is usually a hard constraint that is set up front in the serving framework at the time the model is loaded.</p>
</section>
<section id="preemption-metrics" class="level3">
<h3 class="anchored" data-anchor-id="preemption-metrics">Preemption metrics</h3>
<p>When the system runs out of GPU memory to serve all active requests and their KV caches, something has to give. The scheduler may <strong>preempt</strong> a request, forcing it back to the waiting queue and freeing its KV cache entries to make more memory available. When the preempted request resumes, the system either recomputes its KV cache from scratch or swaps back in the entries it saved in CPU main memory at the time of preemption.</p>
<p>Three metrics diagnose preemption behavior: the <strong>preemption rate</strong> (how often preemption happens), <strong>recomputation overhead</strong> (the extra prefill work to rebuild evicted KV caches), and <strong>swap latency</strong> (the time to move KV cache data between GPU and CPU memory). These are important in high-load scenarios, because a system that preempts too aggressively can waste significant resources on preemption activity. We will cover preemption policies and their tradeoffs in more detail when we discuss scheduling and memory management in <a href="scheduling.html#sec-request-scheduling" class="quarto-xref"><span>Section 5.4</span></a>.</p>
</section>
<section id="putting-it-all-together" class="level3">
<h3 class="anchored" data-anchor-id="putting-it-all-together">Putting it all together</h3>
<p>These metrics are not independent. Increasing batch size improves throughput and MBU but can hurt TTFT and TPOT. High concurrency improves throughput but can increase preemption rate. The art of inference optimization navigates these tradeoffs, trying to maximize user experience while minimizing cost.</p>
</section>
</section>
<section id="sec-workloads" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-workloads"><span class="header-section-number">3.3</span> Workload Patterns</h2>
<p>Not all LLM requests look the same. A one-line classification question and a multi-page document summary put very different demands on the inference system, even if they’re running on the same model with the same hardware. Before we get into the mechanics of how inference systems are built and optimized, it’s worth stepping back and thinking about what kinds of work they’re actually asked to do. The shape of the workload greatly impacts many metrics.</p>
<section id="the-inputoutput-quadrants" class="level3">
<h3 class="anchored" data-anchor-id="the-inputoutput-quadrants">The input/output quadrants</h3>
<p>The simplest way to characterize an LLM workload is by the length of the input and the length of the output. These two dimensions create four quadrants, and each one has a distinct performance profile.</p>
<div id="fig-io-quadrants" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-io-quadrants-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/io_quadrants.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;3.4: The four workload quadrants defined by input and output length"><img src="images/io_quadrants.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-io-quadrants-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.4: The four workload quadrants defined by input and output length
</figcaption>
</figure>
</div>
<p><strong>Short input, short output</strong> is the lightest quadrant. Think of a simple one-off chatbot exchange or a classification task: a sentence or two goes in, and a sentence or two comes out. Prefill is fast because there aren’t many input tokens. Decode is fast because there aren’t many output tokens to generate. The KV cache stays small. Individually, these requests are cheap. For these requests serving systems will achieve the highest requests per minute, because they are so cheap.</p>
<p><strong>Short input, long output</strong> is what you get with creative writing, open-ended code generation, or detailed explanations. Prefill is still quick, but decode dominates the request’s lifetime because the model has to generate hundreds or thousands of tokens sequentially. The KV cache grows with each decode step, so memory pressure increases over the life of the request. For the user, what matters here is the sustained token generation rate — the TPOT we defined in the last section. A slow decode loop means a long wait for the full response.</p>
<p><strong>Long input, short output</strong> is the pattern you see in summarization, information extraction, and retrieval-augmented generation (RAG). A large document or a long retrieved context goes in, and a relatively brief answer comes out. Prefill is expensive because the model has to process a large number of input tokens. But once prefill is done, decode finishes quickly. The KV cache is large from the start, but it doesn’t grow much further. For the user, TTFT is the metric that matters most, since the wait is almost entirely in prefill.</p>
<p><strong>Long input, long output</strong> is the most demanding quadrant. Document translation, detailed analysis with a lengthy report, and long multi-turn conversations all fall here. Prefill is expensive, decode is expensive, and the KV cache is large throughout. These requests consume the most GPU memory and occupy a batch slot for the most time. They’re also the hardest to schedule efficiently alongside other requests, because they consume so many resources.</p>
</section>
<section id="why-the-quadrants-matter" class="level3">
<h3 class="anchored" data-anchor-id="why-the-quadrants-matter">Why the quadrants matter</h3>
<p>The quadrant a request falls into determines where the system’s bottlenecks will show up. Long inputs mean expensive prefills and large initial KV caches. Long outputs mean many decode steps and growing KV caches. Sequence length directly affects how many requests can be batched together, because the KV cache for each active request takes up GPU memory. A batch of long-context requests might only fit a handful of concurrent requests, while a batch of short exchanges might fit many.</p>
<p>In practice, most production workloads are a mix of quadrants. A serving system might see a stream of short chatbot queries punctuated by occasional long summarization requests. The long requests consume disproportionate memory and compute, which can slow down the short requests sharing the same GPU. Managing this mix efficiently is one of the challenges of inference scheduling, which we’ll explore in <a href="scheduling.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
</section>
<section id="batch-vs.-real-time-inference" class="level3">
<h3 class="anchored" data-anchor-id="batch-vs.-real-time-inference">Batch vs.&nbsp;real-time inference</h3>
<p>Beyond the shape of individual requests, the other major dimension of a workload is whether it runs in <strong>batch</strong> (offline) mode or <strong>real-time</strong> (online) mode. This distinction changes which metrics you care about and how aggressively you can optimize.</p>
<p>In <strong>batch inference</strong>, you have a known set of requests to process and no one is waiting on the other end for an immediate response. Maybe the user is scoring a dataset, generating synthetic training data, or running evaluations. The metric that matters most is <strong>throughput</strong> — tokens per second across all requests — and its close relative, <strong>cost per token</strong>. Because there’s no latency constraint, the goal is to take the time to plan the best way to minimize the total cost of processing these requests. You can fill batches to capacity, use cheaper or slower hardware, and let individual requests wait while the system finds the most efficient packing. Larger batches mean better GPU utilization, which means lower cost.</p>
<p>In <strong>real-time inference</strong>, a user (or another system) is waiting for a response, and how fast that response arrives directly affects the experience. Here, the metrics that matter most are <strong>TTFT</strong> and <strong>TPOT</strong>. A chatbot that takes five seconds to start responding feels broken, even if its overall throughput is excellent. This means the serving system has to balance resource utilization against latency. You can’t hold requests in a queue too long to form larger batches, because that increases TTFT for every waiting request.</p>
<p>Some systems serve both kinds of traffic, and some offer different priority tiers — high-priority real-time requests that get scheduled immediately, and lower-priority requests that can wait to fill in the gaps. Batch inference is the easier workload to optimize for, so many of the optimizations in this book will focus on real-time latency issues. The concept of goodput really helps interpret system performance in a way that measures user experience.</p>
</section>
<section id="arrival-patterns" class="level3">
<h3 class="anchored" data-anchor-id="arrival-patterns">Arrival patterns</h3>
<p>The final piece of the workload picture is how requests arrive over time. Even in a real-time serving scenario, the demands on the system vary dramatically depending on the <strong>arrival rate</strong> and its <strong>burstiness</strong>.</p>
<p>If requests arrive at a steady, predictable rate, the system can maintain a stable batch size and keep GPU utilization relatively consistent. But real-world traffic is rarely that well-behaved. User-facing services see spikes — a sudden surge after a product launch, peak hours during the workday, or a viral moment that sends traffic through the roof. During a burst, the system has to either queue requests (increasing latency), drop them, or have enough spare capacity to absorb the spike.</p>
<p>The arrival pattern also affects how well the scheduling system can batch requests together. Requests that arrive close together in time can potentially share a batch. Requests that arrive in isolation may run in small, inefficient batches, wasting GPU compute. The more variable the arrival pattern, the harder it is to maintain consistently high utilization. We’ll see in <a href="scheduling.html#sec-batching" class="quarto-xref"><span>Section 5.1</span></a> how modern schedulers use techniques like continuous batching to adapt dynamically to changing arrival patterns, rather than waiting for a fixed batch to fill up.</p>
<p>In summary, understanding your workload — the mix of input/output lengths, the latency requirements, and the arrival patterns — is one step toward choosing the right optimizations. A system tuned for batch summarization of long documents looks very different from one tuned for low-latency chatbot responses, even though they might be serving the same model.</p>
</section>
</section>
<section id="sec-bottleneck-framework" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-bottleneck-framework"><span class="header-section-number">3.4</span> The Hardware Model and Bottleneck Framework</h2>
<p>In <a href="#sec-inference-pipeline" class="quarto-xref"><span>Section 3.1</span></a>, we explained that prefill is compute-bound and decode is memory-bandwidth-bound. That’s a good start, but to really be able to reason about optimizations more precisely, we need a more detailed picture of the hardware. This section covers just enough GPU architecture to build that picture, then introduces the roofline model as a framework for categorizing compute and memory bandwidth bottlenecks. This won’t be a GPU deep dive or programming tutorial. We’ll cover just enough to understand inference performance quantitatively.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This book focuses on NVIDIA GPUs because they dominate the LLM inference landscape today. However, the bottleneck framework we’re about to introduce applies equally to other hardware. For example, AMD’s MI300X, Google’s TPUs, and other accelerators all have different compute throughput ceilings and memory bandwidth limits, but the same approach to analyzing bottlenecks will work for those devices as well. We will briefly address alternative hardware in <a href="scaling.html" class="quarto-xref"><span>Chapter 7</span></a> when we discuss multi-device deployment.</p>
</div>
</div>
<section id="gpu-compute-throughput" class="level3">
<h3 class="anchored" data-anchor-id="gpu-compute-throughput">GPU compute throughput</h3>
<p>A modern GPU like the NVIDIA H100 is organized around <strong>streaming multiprocessors (SMs)</strong> that do the computing. The H100 SXM has 132 SMs, and each SM contains multiple types of execution units. For LLM inference, the most important of these are the <strong>tensor cores</strong>, the specialized hardware units designed to perform matrix multiplications very fast. Tensor cores are what give modern GPUs their enormous throughput for the matrix multiplications that dominate neural network models. All of the SMs on a GPU are able to simultaneously do work in parallel, which scales up their throughput.</p>
<p>The peak throughput of floating point operations (assuming the SMs don’t ever have to wait for data) depends on the numerical precision you use. Lower precision means more operations per cycle, which translates directly into higher throughput. For the H100 SXM, relative throughput for several data types is shown in <a href="#tbl-precision-tflops" class="quarto-xref">Table&nbsp;<span>3.1</span></a>.</p>
<div id="tbl-precision-tflops" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-precision-tflops-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: Compute throughput figures for the NVIDIA H100 SXM. Source: <span class="citation" data-cites="nvidia2023h100">NVIDIA (<a href="references.html#ref-nvidia2023h100" role="doc-biblioref">2023</a>)</span>.
</figcaption>
<div aria-describedby="tbl-precision-tflops-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<thead>
<tr class="header">
<th>Precision</th>
<th>Peak throughput (TFLOPS)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TF32</td>
<td>494</td>
</tr>
<tr class="even">
<td>FP16</td>
<td>989</td>
</tr>
<tr class="odd">
<td>BF16</td>
<td>989</td>
</tr>
<tr class="even">
<td>FP8</td>
<td>1,987</td>
</tr>
<tr class="odd">
<td>INT8</td>
<td>1,987</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>These numbers are theoretical peaks — the maximum the hardware can deliver if every tensor core is busy on every cycle. In practice, you never hit the peak, but it sets the ceiling. You get roughly double the throughput when you halve the precision. This is one reason quantization (covered in <a href="model-design.html#sec-quantization" class="quarto-xref"><span>Section 4.1</span></a>) is such a useful optimization lever. When you reduce the precision of model weights and activations, you’re saving memory and also increasing compute throughput.</p>
</section>
<section id="the-memory-hierarchy" class="level3">
<h3 class="anchored" data-anchor-id="the-memory-hierarchy">The memory hierarchy</h3>
<p>Raw compute throughput only matters if you can feed data to the tensor cores fast enough. This is where the memory hierarchy comes in. An NVIDIA GPU has four levels of memory, shown in <a href="#fig-gpu-memory-hierarchy" class="quarto-xref">Figure&nbsp;<span>3.5</span></a>. The closest levels are the fastest but also the smallest, and as the levels get larger, they get farther and slower, trading off speed for capacity.</p>
<div id="fig-gpu-memory-hierarchy" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gpu-memory-hierarchy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/gpu_memory_hierarchy.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;3.5: GPU memory hierarchy showing registers, SRAM, L2 cache, and HBM with capacity and bandwidth at each level"><img src="images/gpu_memory_hierarchy.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gpu-memory-hierarchy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.5: GPU memory hierarchy showing registers, SRAM, L2 cache, and HBM with capacity and bandwidth at each level
</figcaption>
</figure>
</div>
<p><strong>Registers</strong> are the fastest storage, private to each thread. They’re plentiful in aggregate (about 256 KB per SM on the H100, totaling roughly 33 MB across all SMs) but each thread running on a SM only sees a small portion. Data in registers is available essentially every clock cycle.</p>
<p><strong>Shared memory and L1 cache (SRAM)</strong> sit on-chip, shared among threads within an SM. On the H100, each SM has 256 KB of combined shared memory and L1 cache, giving about 33 MB total across the chip. SRAM bandwidth is extremely high — on the order of tens of TB/s — but the capacity is small. This is the memory level that custom CUDA kernels like FlashAttention <span class="citation" data-cites="dao2022flashattention">(<a href="references.html#ref-dao2022flashattention" role="doc-biblioref">Dao et al. 2022</a>)</span> exploit. By carefully tiling computations to fit in SRAM, they avoid repeated trips to the much slower main memory.</p>
<p><strong>L2 Cache</strong> is a hardware cache that is not programmable. There is 50 MB of L2 cache total on the H100.</p>
<p><strong>High Bandwidth Memory (HBM)</strong> is the GPU’s main memory. This is the large off-chip memory where model weights, the KV cache, activations, and anything else that’s not transient live. The H100 SXM has 80 GB of HBM3 with a peak bandwidth of approximately 3.35 TB/s. That sounds fast, and it is in absolute terms, but relative to the compute throughput, it’s the bottleneck for most inference workloads. Every byte of model weights that needs to reach a tensor core has to be loaded via HBM’s more limited bandwidth first.</p>
<p>The key insight about the GPU memory architecture is the enormous gap between what the compute units can consume and what HBM can deliver. The tensor cores can perform nearly 990 TFLOPS at FP16 (2 bytes per operand), but the HBM can only deliver 3.35 TB/s. We’ll demonstrate how to compare these numbers in just a moment, when we discuss the roofline model.</p>
</section>
<section id="cpu-gpu-interaction-and-kernel-launch-overhead" class="level3">
<h3 class="anchored" data-anchor-id="cpu-gpu-interaction-and-kernel-launch-overhead">CPU-GPU interaction and kernel launch overhead</h3>
<p>There’s one more piece of hardware context that matters for inference: the CPU-GPU relationship. The GPU is told what to do by the CPU. The CPU orchestrates inference by launching <strong>kernels</strong> — GPU functions that execute on the SMs. Each kernel launch involves the CPU sending a command to the GPU, which has a small but non-zero overhead, typically on the order of 5-10 microseconds.</p>
<p>For a single kernel launch, this overhead is negligible. But a single transformer layer can require multiple kernel launches (matrix multiplications, layer norm, activation functions, attention), and a large model may have 80 or more layers. During decode, where each step generates just one token, the actual computation per kernel can be very small. When you’re launching hundreds of short kernels per decode step, the cumulative launch overhead starts to matter.</p>
<p><strong>CUDA graphs</strong> address this problem. A CUDA graph captures a fixed sequence of kernel launches into a single object that can be replayed with a single launch command. Instead of the CPU issuing multiple individual kernel launches, it replays one graph. This amortizes the launch overhead and can noticeably reduce latency for decode steps. We’ll revisit CUDA graphs in more detail in <a href="request.html" class="quarto-xref"><span>Chapter 6</span></a>, where we’ll also discuss their limitations — primarily that the captured graph must be static, which creates complications when sequence lengths or batch sizes change dynamically.</p>
</section>
<section id="the-bottleneck-framework" class="level3">
<h3 class="anchored" data-anchor-id="the-bottleneck-framework">The bottleneck framework</h3>
<p>With the hardware picture in place, we can now talk about bottlenecks precisely. GPU-based workloads have three potential bottleneck sources:</p>
<ol type="1">
<li><strong>Compute</strong>: the GPU’s arithmetic units can’t perform operations as fast as the rest of the system.</li>
<li><strong>Memory bandwidth</strong>: the GPU can’t move data from HBM to the compute units as fast as the rest of the system.</li>
<li><strong>Inter-device communication</strong>: data can’t move between GPUs (or between CPU and GPU) as fast as the rest of the system.</li>
</ol>
<p>For single-GPU inference, compute and memory bandwidth are the two relevant bottlenecks. Communication becomes critical when you distribute a model across multiple GPUs, which we’ll discuss in <a href="scaling.html" class="quarto-xref"><span>Chapter 7</span></a>. For now, we’ll focus on the first two bottlenecks.</p>
</section>
<section id="the-roofline-model" class="level3">
<h3 class="anchored" data-anchor-id="the-roofline-model">The roofline model</h3>
<p>The <strong>roofline model</strong>, introduced by <span class="citation" data-cites="williams2009roofline">Williams et al. (<a href="references.html#ref-williams2009roofline" role="doc-biblioref">2009</a>)</span>, gives us a simple visual framework for understanding which bottleneck applies to a given workload. The core idea is that every compute workload has a property called <strong>arithmetic intensity</strong> — the ratio of compute operations to bytes of data moved, measured in FLOPs per byte (FLOP/byte). Arithmetic intensity tells you how much work the computational unit does for each byte being read from memory.</p>
<p>The roofline model says that a kernel’s achievable performance is capped by whichever ceiling it hits first:</p>
<ul>
<li>If arithmetic intensity is low (the kernel reads a lot of data but does relatively little math per byte), the kernel is <strong>memory-bandwidth-bound</strong>. Performance is limited by how fast data can be read from HBM, regardless of how much compute is available.</li>
<li>If arithmetic intensity is high (the kernel does a lot of math per byte read), the kernel is <strong>compute-bound</strong>. Performance is limited by the GPU’s peak FLOP/s, regardless of how much bandwidth is available.</li>
</ul>
<p>The crossover point – where the compute ceiling and the bandwidth ceiling intersect – is called the <strong>ridge point</strong>. For a given GPU, the ridge point is simply the ratio of peak compute throughput to peak memory bandwidth.</p>
<div id="tbl-h100-specs" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-h100-specs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.2: Key hardware parameters for the NVIDIA H100 SXM.
</figcaption>
<div aria-describedby="tbl-h100-specs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Peak FP16 throughput</td>
<td>989.4 TFLOPS</td>
</tr>
<tr class="even">
<td>HBM3 capacity</td>
<td>80 GB</td>
</tr>
<tr class="odd">
<td>HBM3 bandwidth</td>
<td>3.35 TB/s</td>
</tr>
<tr class="even">
<td>Ridge point (FP16)</td>
<td>~295 FLOP/byte</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-h100-specs" class="quarto-xref">Table&nbsp;<span>3.2</span></a> summarizes the key hardware parameters for the H100 SXM that we need for the roofline model. For the H100 SXM at FP16, we calculate:</p>
<p><span class="math display">\[\text{Ridge point} = \frac{\text{Peak FLOP/s}}{\text{Peak bandwidth}} = \frac{989.4 \times 10^{12}}{3.35 \times 10^{12}} \approx 295 \text{ FLOP/byte}\]</span></p>
<p>This means that any kernel with an arithmetic intensity below about 295 FLOP/byte is memory-bandwidth-bound on the H100 at FP16 precision. Any kernel above that threshold is compute-bound. The regions we’ve discussed are shown on the roofline plot for the H100 SXM in <a href="#fig-roofline" class="quarto-xref">Figure&nbsp;<span>3.6</span></a>. On the left, the attainable FLOPS equals the bandwidth times the arithmetic intensity, so the slope of the blue line is <span class="math inline">\(3.35 \times 10^{12}\)</span>. On the right, the attainable FLOPS is capped at the peak of <span class="math inline">\(989.4 \times 10^{12}\)</span>.</p>
<div id="fig-roofline" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-roofline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/roofline.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;3.6: Roofline plot for the H100 SXM at FP16"><img src="images/roofline.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roofline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.6: Roofline plot for the H100 SXM at FP16
</figcaption>
</figure>
</div>
<p>If we were calculating the roofline plot for FP8, the peak bandwidth remains the same, but the peak throughput is about double at 1,979 TFLOPS. The blue line would be extended further up to the right before it hit our 1,979 TFLOPS compute ceiling, so our ridge point would be further right, at 591 FLOP/byte. When you increase compute throughput through lower precision, the bar for being compute-bound gets higher. This means that switching to FP8 can actually make some workloads that were compute-bound at FP16 become memory-bandwidth-bound at FP8. For this reason, workloads don’t always run twice as fast when switching from FP16 to FP8. We will revisit this in <a href="model-design.html#sec-quantization" class="quarto-xref"><span>Section 4.1</span></a> when we discuss model quantization.</p>
</section>
</section>
<section id="sec-prefill-decode" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-prefill-decode"><span class="header-section-number">3.5</span> Putting Numbers on a Baseline</h2>
<p>With the roofline model in hand, let’s look at real numbers for prefill and decode. We’ll use the NVIDIA H100 SXM as our reference hardware and a 70-billion-parameter model as our reference model. The goal is to establish a <strong>baseline</strong> for inference without any optimizations. Every technique in the rest of this book is an improvement on this baseline.</p>
<section id="sec-prefill-stage" class="level3">
<h3 class="anchored" data-anchor-id="sec-prefill-stage">Prefill is compute-bound</h3>
<p>During prefill, the model processes <strong><span class="dim-s">S</span></strong> input tokens in one forward pass. A large, fixed cost is the matrix multiplications in the attention projections and MLP layers. A widely used approximation for the total FLOPs of a forward pass is:</p>
<p><span class="math display">\[\text{FLOPS}_{\text{prefill}} \approx 2 \times P \times S\]</span></p>
<p>where <span class="math inline">\(P\)</span> is the number of model parameters and <strong><span class="dim-s">S</span></strong> is the number of input tokens. The factor of 2 comes from the fact that each parameter participates in one multiply and one add (a multiply-accumulate operation counts as 2 FLOPs). This approximation covers the linear layers and is reasonably accurate for large models where attention’s quadratic component is small relative to the total.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This <span class="math inline">\(2 \times P \times S\)</span> approximation counts the FLOPs for the linear projections (QKV projections, output projection, and MLP layers). It omits the quadratic attention score computation (<span class="math inline">\(O(S^2 \times d_{\text{head}} \times H \times L)\)</span>) and smaller operations like layer norms and activations. For very long sequences, the <span class="math inline">\(S^2\)</span> in the attention cost becomes significant, and adds even more to the arithmetic intensity.</p>
</div>
</div>
<p>For our 70B model with <span class="math inline">\(S = 4{,}096\)</span> input tokens:</p>
<p><span class="math display">\[\text{FLOPs}_{\text{prefill}} \approx 2 \times 70 \times 10^9 \times 4{,}096 = 5.73 \times 10^{14} \text{ FLOPs} \approx 573 \text{ TFLOP}\]</span></p>
<p>Now let’s compute the arithmetic intensity. The data that must be read from HBM during prefill is primarily the model weights (the input activations for the first layer come from the embedding lookup and are small by comparison). In FP16, the weights occupy:</p>
<p><span class="math display">\[\text{Weight bytes} = 70 \times 10^9 \times 2 = 140 \text{ GB}\]</span></p>
<p>The arithmetic intensity is:</p>
<p><span class="math display">\[\text{AI}_{\text{prefill}} = \frac{573 \times 10^{12}}{140 \times 10^9} \approx 4{,}093 \text{ FLOP/byte}\]</span></p>
<p>Recall from <a href="#sec-bottleneck-framework" class="quarto-xref"><span>Section 3.4</span></a> that the H100 SXM ridge point at FP16 is approximately 295 FLOP/byte. Our prefill arithmetic intensity of ~4,093 FLOP/byte is more than <strong>13x above the ridge point</strong>. Prefill is firmly in compute-bound territory.</p>
<p>What does this mean for execution time? Since we’re compute-bound, the time is limited by the GPU’s peak compute throughput:</p>
<p><span class="math display">\[t_{\text{prefill}} \geq \frac{573 \times 10^{12}}{989.5 \times 10^{12}} \approx 0.58 \text{ seconds}\]</span></p>
<p>In practice, you won’t achieve 100% of peak throughput due to overhead, memory access patterns that aren’t perfectly optimized, and the attention computation. A realistic MFU of 50-70% would put the actual prefill time at roughly 0.8-1.2 seconds for this workload.</p>
<p>Notice what happens as the prompt gets shorter. With <span class="math inline">\(S = 256\)</span> tokens:</p>
<p><span class="math display">\[\text{AI}_{\text{prefill}} = \frac{2 \times 70 \times 10^9 \times 256}{140 \times 10^9} = 256 \text{ FLOP/byte}\]</span></p>
<p>That’s just below the H100’s ridge point of 295. Very short prompts could push prefill toward the memory-bandwidth-bound side, though in practice long system prompts tend to prevent requests from ever being this short.</p>
</section>
<section id="sec-decode-stage" class="level3">
<h3 class="anchored" data-anchor-id="sec-decode-stage">Decode is memory-bandwidth-bound</h3>
<p>Now consider a single decode step with batch size 1. The model runs a forward pass for just one new token. The approximate FLOPs are:</p>
<p><span class="math display">\[\text{FLOPs}_{\text{decode}} \approx 2 \times P \times 1 = 2 \times 70 \times 10^9 = 140 \times 10^9 \text{ FLOPs} = 140 \text{ GFLOP}\]</span></p>
<p>But the data movement is nearly the same as prefill — the GPU still has to read all the model weights from HBM:</p>
<p><span class="math display">\[\text{Weight bytes} = 140 \text{ GB}\]</span></p>
<p>The arithmetic intensity calculated using only the weight reads is:</p>
<p><span class="math display">\[\text{AI}_{\text{decode}} = \frac{140 \times 10^9}{140 \times 10^9} = 1 \text{ FLOP/byte}\]</span></p>
<p>One FLOP per byte. The H100’s ridge point is 295 FLOP/byte. We are <strong>295x below the ridge point</strong>. Decode is deeply, profoundly memory-bandwidth-bound.</p>
<p>This is the central quantitative insight of LLM inference. During decode, the GPU reads 140 GB of weight data to perform just 140 GFLOP of computation. The tensor cores are capable of nearly 990 TFLOP/s, but they’re starved for data. The bottleneck in this scenario is how fast the GPU can stream weights from HBM.</p>
<p>The minimum time for a single decode step is bounded by the time to read the weights:</p>
<p><span class="math display">\[t_{\text{decode}} \geq \frac{140 \text{ GB}}{3.35 \text{ TB/s}} \approx 41.8 \text{ ms}\]</span></p>
<p>At one decode step per output token, that’s a theoretical maximum of about 24 tokens per second for a single request. In practice, accounting for KV cache reads and other overhead, you might see 15-20 tokens per second for a batch-1, 70B FP16 model on an H100 – comfortably in the range where text streaming feels smooth, but not exactly fast.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is why quantization has such a dramatic effect on decode speed. If you quantize the weights from FP16 (2 bytes) to INT4 (0.5 bytes), the weight data drops from 140 GB to 35 GB. The minimum decode step time drops to <span class="math inline">\(35 / 3{,}350 \approx 10.4\)</span> ms, roughly 4x faster. The arithmetic intensity goes from 1 to 4 FLOP/byte — still far below the INT4 ridge point, so you’re still bandwidth-bound, but you’ve reduced by 4x the bandwidth needed. So, not only does quantization help fit models into GPU memory, it also speeds up inference. We’ll cover quantization in detail in <a href="model-design.html#sec-quantization" class="quarto-xref"><span>Section 4.1</span></a>.</p>
</div>
</div>
</section>
<section id="the-kv-cache-adds-to-reads-and-writes" class="level3">
<h3 class="anchored" data-anchor-id="the-kv-cache-adds-to-reads-and-writes">The KV cache adds to reads and writes</h3>
<p>The analysis above only accounts for reading the model weights. But during decode, the attention computation also reads the full KV cache – all the keys and values from all previous tokens, across all layers.</p>
<p>For our 70B model with 80 layers, 8 KV heads, head dimension 128, and FP16 entries, the KV cache after processing a total of <strong><span class="dim-s">S</span></strong> tokens (input + output so far) is:</p>
<p><span class="math display">\[\text{KV cache size} = 2 \times 80 \times 8 \times 128 \times S \times 2 = 327{,}680 \times S \text{ bytes}\]</span></p>
<p>After a 4,096-token prefill and 512 tokens of decode (<span class="math inline">\(S = 4{,}608\)</span>):</p>
<p><span class="math display">\[\text{KV cache} \approx 1.51 \text{ GB}\]</span></p>
<p>This adds to the data that must be read from HBM at every decode step. The total bytes read per decode step becomes:</p>
<p><span class="math display">\[\text{Total bytes} = \underbrace{140 \text{ GB}}_{\text{weights}} + \underbrace{1.51 \text{ GB}}_{\text{KV cache}} \approx 141.5 \text{ GB}\]</span></p>
<p>For a 70B model, this KV cache is a relatively small addition – about 1% of the total data read. But consider a smaller model. For a longer sequence, such as <span class="math inline">\(S = 100{,}000\)</span>, the KV cache would be ~33 GB. At these lengths, KV cache bandwidth becomes a significant factor in decode time.</p>
<p>The KV cache also grows by one entry per layer per KV head per decode step. Each step must write:</p>
<p><span class="math display">\[\Delta \text{KV cache} = 2 \times L \times H_{\text{kv}} \times d_{\text{head}} \times b_{\text{kv}}\]</span></p>
<p>For our 70B model: <span class="math inline">\(2 \times 80 \times 8 \times 128 \times 2 = 327{,}680\)</span> bytes <span class="math inline">\(\approx 320\)</span> KB per decode step. This is a small amount of data to write, but the cumulative effect is what matters: the KV cache grows monotonically, and every subsequent decode step has to read the entire thing.</p>
</section>
<section id="batching-changes-the-picture" class="level3">
<h3 class="anchored" data-anchor-id="batching-changes-the-picture">Batching changes the picture</h3>
<p>So far, we’ve analyzed decode with batch size 1 — a single request in isolation. This is the worst case for GPU utilization. The key insight is that <strong>batching multiple requests together improves arithmetic intensity</strong> by amortizing the weight reads across more tokens.</p>
<p>When you batch <span class="math inline">\(B\)</span> requests together, each decode step processes <span class="math inline">\(B\)</span> tokens instead of 1. The model weights are read once and applied to all <span class="math inline">\(B\)</span> tokens. The FLOPs scale linearly with <span class="math inline">\(B\)</span>:</p>
<p><span class="math display">\[\text{FLOPs}_{\text{batch}} \approx 2 \times P \times B\]</span></p>
<p>But the weight data read stays constant at <span class="math inline">\(P \times b_w\)</span> bytes (where <span class="math inline">\(b_w\)</span> is bytes per weight). The arithmetic intensity for the weight multiplications becomes:</p>
<p><span class="math display">\[\text{AI}_{\text{batch}} = \frac{2 \times P \times B}{P \times b_w} = \frac{2B}{b_w}\]</span></p>
<p>For FP16 weights (<span class="math inline">\(b_w = 2\)</span>), we end up with <span class="math inline">\(\text{AI}_{\text{batch}} = B \text{ FLOP/byte}\)</span>.</p>
<table class="caption-top table">
<caption>Arithmetic intensity of decode steps as a function of batch size for FP16 weights on H100 SXM. The ridge point is ~295 FLOP/byte.</caption>
<thead>
<tr class="header">
<th>Batch size</th>
<th>Arithmetic intensity (FLOP/byte)</th>
<th>Regime on H100</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>Bandwidth-bound</td>
</tr>
<tr class="even">
<td>8</td>
<td>8</td>
<td>Bandwidth-bound</td>
</tr>
<tr class="odd">
<td>32</td>
<td>32</td>
<td>Bandwidth-bound</td>
</tr>
<tr class="even">
<td>128</td>
<td>128</td>
<td>Bandwidth-bound</td>
</tr>
<tr class="odd">
<td>295</td>
<td>295</td>
<td>Ridge point</td>
</tr>
<tr class="even">
<td>512</td>
<td>512</td>
<td>Compute-bound</td>
</tr>
</tbody>
</table>
<div id="fig-roofline-batching" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-roofline-batching-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/roofline_batching.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;3.7: Roofline plot showing decode operating points at different batch sizes. Each point sits on the roofline at arithmetic intensity equal to the batch size (for FP16 weights). Batching moves the operating point rightward, from deeply bandwidth-bound toward the compute ceiling."><img src="images/roofline_batching.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roofline-batching-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.7: Roofline plot showing decode operating points at different batch sizes. Each point sits on the roofline at arithmetic intensity equal to the batch size (for FP16 weights). Batching moves the operating point rightward, from deeply bandwidth-bound toward the compute ceiling.
</figcaption>
</figure>
</div>
<p>This is the fundamental reason batching helps decode throughput. With batch size 1, you’re reading 140 GB to do around 140 GFLOP of work. With batch size 128, you’re reading the same 140 GB but doing 18 TFLOP of work. You’re moving rightward on the roofline, getting more useful computation per byte read.</p>
<p>The throughput gain is substantial. At batch size 1, the decode throughput is bounded by bandwidth at about 24 tokens/s. At batch size 128, you’re still bandwidth-bound but now generating 128 tokens per step, so the throughput is approximately <span class="math inline">\(128 \times 24 \approx 3{,}072\)</span> tokens/s across all requests. Each individual request still sees about 24 tokens/s (the step time is the same because we’re reading the same weight data), but the system throughput has increased 128x.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This first order analysis ignores the KV cache reads, which do scale with batch size, since each request has its own KV cache. At large batch sizes with long sequences, the KV cache bandwidth can become a significant additional cost. It also ignores the memory capacity constraint: each active request’s KV cache occupies HBM, so the maximum batch size is limited by how many KV caches fit in memory alongside the model weights.</p>
</div>
</div>
<p>To push the arithmetic intensity above the ridge point and become compute-bound, you’d need a batch size of about 295 for FP16 weights on the H100. In practice, memory capacity limits usually prevent batch sizes this large for big models. A 70B model with 140 GB of weights leaves only ~40 GB for KV caches on an 80 GB GPU. If each request’s KV cache is 1.5 GB, you can fit about 26 concurrent requests – far short of the 295 needed to hit the ridge point. This is why decode for large models remains memory-bandwidth-bound even with batching, and why the optimizations in <a href="request.html#sec-kv-cache" class="quarto-xref"><span>Section 6.3</span></a> for reducing KV cache memory usage are so important – they enable larger batch sizes, which improves throughput.</p>
</section>
<section id="back-of-envelope-summary" class="level3">
<h3 class="anchored" data-anchor-id="back-of-envelope-summary">Back-of-envelope summary</h3>
<p>Let’s collect the key numbers for our reference configuration: a 70B parameter model in FP16 on an H100 SXM (80 GB HBM, 3.35 TB/s bandwidth, 989.5 TFLOP/s FP16).</p>
<table class="caption-top table">
<caption>Back-of-envelope performance for a 70B FP16 model on H100 SXM. Prefill throughput is computed as <span class="math inline">\(S / t_\text{prefill}\)</span>. Decode throughput is <span class="math inline">\(B / t_\text{decode}\)</span>. These are theoretical lower bounds on step time; real-world performance will be somewhat lower.</caption>
<colgroup>
<col style="width: 24%">
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th>Prefill (S=4096)</th>
<th>Decode (B=1)</th>
<th>Decode (B=32)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FLOPs per step</td>
<td>573 TFLOP</td>
<td>140 GFLOP</td>
<td>4.48 TFLOP</td>
</tr>
<tr class="even">
<td>Data read (weights)</td>
<td>140 GB</td>
<td>140 GB</td>
<td>140 GB</td>
</tr>
<tr class="odd">
<td>Arithmetic intensity</td>
<td>~4,093 FLOP/byte</td>
<td>~1 FLOP/byte</td>
<td>~32 FLOP/byte</td>
</tr>
<tr class="even">
<td>Bottleneck</td>
<td>Compute</td>
<td>Bandwidth</td>
<td>Bandwidth</td>
</tr>
<tr class="odd">
<td>Min step time</td>
<td>~0.58 s (compute)</td>
<td>~41.8 ms (bandwidth)</td>
<td>~41.8 ms (bandwidth)</td>
</tr>
<tr class="even">
<td>Tokens per step</td>
<td>4,096 (all input)</td>
<td>1</td>
<td>32</td>
</tr>
<tr class="odd">
<td>Throughput</td>
<td>~7,000 tok/s</td>
<td>~24 tok/s</td>
<td>~766 tok/s</td>
</tr>
</tbody>
</table>
<p>A few things stand out from this table:</p>
<ol type="1">
<li><p><strong>Prefill processes tokens roughly 300x more efficiently than batch-1 decode</strong>, in terms of tokens produced per second. This is the direct consequence of the arithmetic intensity gap.</p></li>
<li><p><strong>Batching is the single most important lever for decode throughput.</strong> Going from batch size 1 to 32 increases system throughput by 32x with essentially no increase in step time, because we’re bandwidth-bound either way – the same weight data is read, just applied to more tokens.</p></li>
<li><p><strong>The step time for decode barely changes with batch size</strong> (as long as we remain bandwidth-bound). This means that batching increases <em>system</em> throughput without significantly increasing per-request latency – a rare win-win, limited mainly by available memory for KV caches.</p></li>
<li><p><strong>Weight memory dominates the data read for large models.</strong> The KV cache is a relatively small fraction of the total data read per step, though it becomes more significant for smaller models and longer sequences.</p></li>
</ol>
<p>These numbers are the baseline that every optimization in subsequent chapters maps onto. When we discuss quantization in <a href="model-design.html#sec-quantization" class="quarto-xref"><span>Section 4.1</span></a>, we’ll see how reducing bytes per weight directly reduces the bandwidth denominator. When we discuss batching strategies in <a href="scheduling.html#sec-batching" class="quarto-xref"><span>Section 5.1</span></a>, we’ll see how continuous batching and chunked prefill allow the system to maintain high batch sizes. When we discuss KV cache optimizations in <a href="request.html#sec-kv-cache" class="quarto-xref"><span>Section 6.3</span></a>, we’ll see how reducing KV cache memory enables larger batches. And when we discuss speculative decoding in <a href="request.html#sec-speculative" class="quarto-xref"><span>Section 6.5</span></a>, we’ll see how generating multiple tokens per decode step changes the numerator.</p>
</section>
</section>
<section id="map-of-the-optimizations" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="map-of-the-optimizations"><span class="header-section-number">3.6</span> Map of the optimizations</h2>
<p>The next four chapters in this book each focus on a specific class of bottleneck and the techniques that address it:</p>
<table class="caption-top table">
<caption>How each chapter maps to the bottleneck framework.</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 43%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Chapter</th>
<th>Bottleneck class</th>
<th>Core lever</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="model-design.html" class="quarto-xref"><span>Chapter 4</span></a> – Model Reduction</td>
<td>Model size and compute</td>
<td>Reduce cost per token via decreasing model size</td>
</tr>
<tr class="even">
<td><a href="scheduling.html" class="quarto-xref"><span>Chapter 5</span></a> – Scheduling and Batching</td>
<td>Pipeline and scheduling</td>
<td>Reduce wasted GPU resources through smarter batching and memory management</td>
</tr>
<tr class="odd">
<td><a href="request.html" class="quarto-xref"><span>Chapter 6</span></a> – Request-Level Optimizations</td>
<td>Request compute and memory; sequential decoding</td>
<td>Optimize individual requests; break the sequential decoding constraint</td>
</tr>
<tr class="even">
<td><a href="scaling.html" class="quarto-xref"><span>Chapter 7</span></a> – Multi-Device Inference</td>
<td>Hardware capacity</td>
<td>Distribute across devices when one GPU isn’t enough</td>
</tr>
</tbody>
</table>
<p>This bottleneck framework gives you a way to evaluate any optimization you encounter: what bottleneck does it address, and does that bottleneck actually apply to your workload? An optimization that reduces compute won’t help a memory-bandwidth-bound decode step much. A technique that reduces memory traffic won’t help a compute-bound prefill. Keeping the roofline in mind as you read the rest of this book will help you understand not just <em>what</em> each technique does, but <em>why</em> it works and <em>when</em> it helps.</p>
<p>The book concludes in <a href="production.html" class="quarto-xref"><span>Chapter 8</span></a> with a discussion of production LLM serving systems.</p>
</section>
<section id="further-reading" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">3.7</span> Further Reading</h2>
<p>The Anyscale blog post on reproducible performance metrics <span class="citation" data-cites="anyscale2024metrics">(<a href="references.html#ref-anyscale2024metrics" role="doc-biblioref">Kadous et al. 2023</a>)</span> is a practical guide to LLM inference metrics, including many of the ones introduced in this chapter, such as TTFT, TPOT, throughput, and goodput.</p>
<p>The NVIDIA Hopper architecture blog post <span class="citation" data-cites="nvidia2024hopper">(<a href="references.html#ref-nvidia2024hopper" role="doc-biblioref">NVIDIA 2022</a>)</span> provides detailed block diagrams of the H100’s SM and full-chip layout, including the memory hierarchy, tensor core organization, and the Tensor Memory Accelerator. <span class="citation" data-cites="gu2024gpusbrrr">Gu and Dao (<a href="references.html#ref-gu2024gpusbrrr" role="doc-biblioref">2024</a>)</span> from Hazy Research gives a practitioner-oriented walkthrough of GPU memory levels with concrete bandwidth numbers at each tier, which is useful context for understanding why kernel design choices matter so much for inference performance. For a detailed empirical look at the H100’s L2 cache behavior and measured bandwidth at different access patterns, <span class="citation" data-cites="chipsandcheese2023h100">Chips and Cheese (<a href="references.html#ref-chipsandcheese2023h100" role="doc-biblioref">2023</a>)</span> is an informative deep dive.</p>
<p>For GPU hardware specifics, the NVIDIA H100 datasheet <span class="citation" data-cites="nvidia2023h100">(<a href="references.html#ref-nvidia2023h100" role="doc-biblioref">NVIDIA 2023</a>)</span> and the CUDA Programming Guide <span class="citation" data-cites="nvidia2024cuda">(<a href="references.html#ref-nvidia2024cuda" role="doc-biblioref">NVIDIA 2024</a>)</span> are the authoritative references. The datasheet gives the peak throughput and bandwidth numbers used throughout this book. The programming guide covers the memory hierarchy, kernel launch mechanics, and CUDA graphs in much more detail than we do here.</p>
<p>The back-of-envelope analysis in this chapter follows the approach laid out by <span class="citation" data-cites="pope2022scaling">Pope et al. (<a href="references.html#ref-pope2022scaling" role="doc-biblioref">2022</a>)</span>, who provide a thorough accounting of FLOPs, memory bandwidth, and arithmetic intensity for each layer of a transformer during inference. Their paper covers both prefill and decode on TPU hardware, but the methodology translates directly to GPUs. They also cover the effects of multi-query attention, different parallelism strategies, and how the roofline picture changes as you scale model size.</p>
<p>For an accessible walkthrough of counting parameters and FLOPs in transformer models, Kipply’s “Transformer Inference Arithmetic” <span class="citation" data-cites="kipply2023arithmetic">(<a href="references.html#ref-kipply2023arithmetic" role="doc-biblioref">Chen 2022</a>)</span> is an excellent companion to this chapter. It works through the same kinds of calculations we’ve done here – parameter counts, memory footprints, FLOPs per layer – with clear explanations of where each number comes from.</p>
<p>For a broader survey of LLM inference techniques and how they fit together, <span class="citation" data-cites="miao2023efficient">Miao et al. (<a href="references.html#ref-miao2023efficient" role="doc-biblioref">2023</a>)</span> covers the full landscape from model compression through serving system design. It’s a useful map of the territory before diving into the detailed treatments in the chapters that follow.</p>
<p>The roofline model was introduced by <span class="citation" data-cites="williams2009roofline">Williams et al. (<a href="references.html#ref-williams2009roofline" role="doc-biblioref">2009</a>)</span> and remains one of the clearest frameworks for reasoning about hardware bottlenecks. Their original paper uses CPU examples, but the model applies directly to GPUs – the key insight is the same: compare arithmetic intensity against the ridge point to determine whether you’re compute-bound or bandwidth-bound.</p>
<p>A comprehensive, in-depth treatment of hardware performance is in “How to Scale Your Model” <span class="citation" data-cites="austin2025scaling">(<a href="references.html#ref-austin2025scaling" role="doc-biblioref">Austin et al. 2025</a>)</span>. This book primarily focuses on TPUs, with one specific chapter on GPUs. All of the concepts apply to whatever hardware you have.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-austin2025scaling" class="csl-entry" role="listitem">
Austin, Jacob, Sholto Douglas, Roy Frostig, et al. 2025. <span>“How to Scale Your Model.”</span> <a href="https://jax-ml.github.io/scaling-book/">https://jax-ml.github.io/scaling-book/</a>.
</div>
<div id="ref-kipply2023arithmetic" class="csl-entry" role="listitem">
Chen, Carol. 2022. <span>“Transformer Inference Arithmetic.”</span> <a href="https://kipp.ly/transformer-inference-arithmetic/">https://kipp.ly/transformer-inference-arithmetic/</a>.
</div>
<div id="ref-chipsandcheese2023h100" class="csl-entry" role="listitem">
Chips and Cheese. 2023. <span>“Nvidia’s <span>H100</span>: Funny <span>L2</span>, and Tons of Bandwidth.”</span> <a href="https://chipsandcheese.com/2023/07/02/nvidias-h100-funny-l2-and-tons-of-bandwidth/">https://chipsandcheese.com/2023/07/02/nvidias-h100-funny-l2-and-tons-of-bandwidth/</a>.
</div>
<div id="ref-chowdhery2022palm" class="csl-entry" role="listitem">
<span class="nocase">Chowdhery, Aakanksha, Sharan Narang, Jacob Devlin, et al.</span> 2022. <span>“<span>PaLM</span>: Scaling Language Modeling with Pathways.”</span> <em>arXiv Preprint arXiv:2204.02311</em>. <a href="https://arxiv.org/abs/2204.02311">https://arxiv.org/abs/2204.02311</a>.
</div>
<div id="ref-dao2022flashattention" class="csl-entry" role="listitem">
Dao, Tri, Daniel Y. Fu, Stefano Ermon, Atri Rudra, and Christopher Ré. 2022. <span>“<span>FlashAttention</span>: Fast and Memory-Efficient Exact Attention with <span>IO</span>-Awareness.”</span> <em>arXiv Preprint arXiv:2205.14135</em>. <a href="https://arxiv.org/abs/2205.14135">https://arxiv.org/abs/2205.14135</a>.
</div>
<div id="ref-gu2024gpusbrrr" class="csl-entry" role="listitem">
Gu, Albert, and Tri Dao. 2024. <span>“<span>GPUs</span> Go Brrr.”</span> <a href="https://hazyresearch.stanford.edu/blog/2024-05-12-tk">https://hazyresearch.stanford.edu/blog/2024-05-12-tk</a>.
</div>
<div id="ref-anyscale2024metrics" class="csl-entry" role="listitem">
Kadous, Waleed, Kyle Huang, Wendi Ding, Liguang Xie, Avnish Narayan, and Ricky Xu. 2023. <span>“Reproducible Performance Metrics for <span>LLM</span> Inference.”</span> <a href="https://www.anyscale.com/blog/reproducible-performance-metrics-for-llm-inference">https://www.anyscale.com/blog/reproducible-performance-metrics-for-llm-inference</a>.
</div>
<div id="ref-miao2023efficient" class="csl-entry" role="listitem">
Miao, Xupeng, Gabriele Oliaro, Zhihao Zhang, et al. 2023. <span>“Towards Efficient Generative Large Language Model Serving: A Survey from Algorithms to Systems.”</span> <em>arXiv Preprint arXiv:2312.15234</em>. <a href="https://arxiv.org/abs/2312.15234">https://arxiv.org/abs/2312.15234</a>.
</div>
<div id="ref-nvidia2024hopper" class="csl-entry" role="listitem">
NVIDIA. 2022. <span>“<span>NVIDIA</span> Hopper Architecture in-Depth.”</span> <a href="https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/">https://developer.nvidia.com/blog/nvidia-hopper-architecture-in-depth/</a>.
</div>
<div id="ref-nvidia2023h100" class="csl-entry" role="listitem">
NVIDIA. 2023. <span>“<span>NVIDIA H100 Tensor Core GPU</span>.”</span> <a href="https://www.nvidia.com/en-us/data-center/h100/">https://www.nvidia.com/en-us/data-center/h100/</a>.
</div>
<div id="ref-nvidia2024cuda" class="csl-entry" role="listitem">
NVIDIA. 2024. <span>“<span>CUDA</span> Programming Guide.”</span> <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/">https://docs.nvidia.com/cuda/cuda-programming-guide/</a>.
</div>
<div id="ref-pope2022scaling" class="csl-entry" role="listitem">
Pope, Reiner, Sholto Douglas, Aakanksha Chowdhery, et al. 2022. <span>“Efficiently Scaling Transformer Inference.”</span> <em>arXiv Preprint arXiv:2211.05102</em>. <a href="https://arxiv.org/abs/2211.05102">https://arxiv.org/abs/2211.05102</a>.
</div>
<div id="ref-spheron2025benchmarks" class="csl-entry" role="listitem">
Spheron. 2025. <span>“<span class="nocase">vLLM</span> Vs <span>TensorRT-LLM</span> Vs <span>SGLang</span>: Benchmarks on <span>H100</span>.”</span> <a href="https://www.spheron.network/blog/vllm-vs-tensorrt-llm-vs-sglang-benchmarks/">https://www.spheron.network/blog/vllm-vs-tensorrt-llm-vs-sglang-benchmarks/</a>.
</div>
<div id="ref-williams2009roofline" class="csl-entry" role="listitem">
Williams, Samuel, Andrew Waterman, and David Patterson. 2009. <span>“Roofline: An Insightful Visual Performance Model for Multicore Architectures.”</span> <em>Communications of the ACM</em> 52 (4): 65–76. <a href="https://dl.acm.org/doi/pdf/10.1145/1498765.1498785">https://dl.acm.org/doi/pdf/10.1145/1498765.1498785</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/decoder-only-llm.html" class="pagination-link" aria-label="The Decoder-Only Transformer">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Decoder-Only Transformer</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/model-design.html" class="pagination-link" aria-label="Model Design Choices">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Model Design Choices</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/tedkyi/llm-inference/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>